name: Dodatek 1b

on:
  push:
    branches: [main]

jobs:
  build-push-images:
    name: Budowanie obrazów i przesyłanie ich na Docker Hub
    runs-on: ubuntu-latest

    steps:

      # Akcja sprawdzająca kod
      - name: Checkout code
        uses: actions/checkout@v2

      # Akcja instalująca i konfigurująca QEMU
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      # Akcja instalująca i konfigurująca Buildx
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1

      # Logowanie na GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.GHCR_TOKEN }}