name: Dodatek 1b

on:
  push:
    branches: [main]

jobs:
  build-push-images:
    name: Budowanie obrazów i przesyłanie ich na Docker Hub
    runs-on: ubuntu-latest

    steps:

      # Akcja sprawdzająca kod
      - name: Checkout code
        uses: actions/checkout@v2

      # Akcja instalująca i konfigurująca QEMU
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      # Akcja instalująca i konfigurująca Buildx
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1

      # Logowanie na GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.GHCR_TOKEN }}

      # Budowanie i publikacja gotowych obrazów na GitHub Container Registry - repozytorium zad1dod1, tag serwer, platformy amd64, armv7 i arm64, eksport cache
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          file: ./Dockerfile
          push: true
          tags: ghcr.io/djkrnl/zad1:dod1
          cache-from: type=registry,ref=ghcr.io/djkrnl/zad1:dod1
          cache-to: type=inline